//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enpratik.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_Role_Authentications
    {
        public int Id { get; set; }
        public Nullable<int> SubMenuId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public Nullable<int> ModuleActionId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedUserId { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int UpdatedUserId { get; set; }
        public System.DateTime DeletedDate { get; set; }
        public int DeletedUserId { get; set; }
        public bool IsActive { get; set; }
    }
}
