//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enpratik.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Admin_MainMenu
    {
        public int Id { get; set; }
        [Display(Name = "Menü Adı")]
        [Required(ErrorMessage = "Menü Adı Giriniz")]
        public string MainMenuName { get; set; }
        public string Link { get; set; }
        public Nullable<int> OrderIndex { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CssName { get; set; }
    }
}
