//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enpratik.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_Module_Actions
    {
        public int Id { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public string ActionName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
    public class Admin_Module_ActionsDTO
    {
        public int Id { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public string ActionName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ModuleName { get; set; }
    }
}
