//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enpratik.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_SubMenu
    {
        public int Id { get; set; }
        public Nullable<int> MainMenuId { get; set; }
        public string MenuName { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public Nullable<int> ActionId { get; set; }
        public string ActionParams { get; set; }
        public Nullable<int> OrderIndex { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
    public class Admin_SubMenuDTO
    {
        public int Id { get; set; }
        public Nullable<int> MainMenuId { get; set; }
        public string MainMenuName { get; set; }
        public string MenuName { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public Nullable<int> ActionId { get; set; }
        public string ActionParams { get; set; }
        public Nullable<int> OrderIndex { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
