//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enpratik.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CargoCompanies
    {
        public int Id { get; set; }
        [Display(Name = "Karfo Firma Adı")]
        [Required(ErrorMessage = "Karfo Firma Adı Giriniz!")]
        public string CargoName { get; set; }
        [Display(Name = "Kargo Firma İkonu")]
        public string CargoIconUrl { get; set; }
        [Display(Name = "Kapıda Ödeme")]
        public Nullable<bool> IsPayAtTheDoor { get; set; }
        [Display(Name = "Kapıda Kredi Kartı İle Ödeme")]
        public Nullable<bool> IsPayAtTheDoorKK { get; set; }
        public Nullable<int> LanguageId { get; set; }
        [Display(Name = "Yayınla")]
        public Nullable<bool> IsPublished { get; set; }
        [Display(Name = "Oluşturulma Tarihi")]
        public Nullable<System.DateTime> CreatedDate { get; set; }
        [Display(Name = "Oluşturan Kişi")]
        public Nullable<int> CreatedUserId { get; set; }
        [Display(Name = "Güncelleme Tarihi")]
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        [Display(Name = "Güncelleyen Kişi")]
        public Nullable<int> UpdatedUserId { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> DeletedUserId { get; set; }
        [Display(Name = "Aktif mi")]
        public Nullable<bool> IsActive { get; set; }
    }
}
