//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enpratik.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data;
    using System.Linq;

    public partial class Categories
    {
        public int Id { get; set; }
        [Display(Name = "Dil")]
        [Required(ErrorMessage = "Dil Seçiniz!")]
        public int LanguageId { get; set; }

        [Display(Name = "Üst Kategori")]
        public int ParentId { get; set; }

        [Display(Name = "Kategori Adı")]
        [Required(ErrorMessage = "Kategori Adı Giriniz!")]
        public string CategoryName { get; set; }

        public int UrlId { get; set; }

        [Display(Name = "Kategori Açıklama")]

        public string CategoryDescription { get; set; }

        [Display(Name = "Seo Anahtar Kelimeler")]
        public string MetaKeywords { get; set; }

        [Display(Name = "Seo Açıklama")]
        public string MetaDescription { get; set; }

        [Display(Name = "Seo Site Başlığı")]
        public string MetaTitle { get; set; }

        [Display(Name = "Kategori Resim")]
        public string CategoryImageUrl { get; set; }

        [Display(Name = "Yayınla")]
        public bool Published { get; set; }

        [Display(Name = "Görüntüleme Sırası")]
        public Nullable<int> DisplayOrder { get; set; }

        [Display(Name = "Oluşturulma Tarihi")]
        public Nullable<System.DateTime> CreatedDate { get; set; }

        [Display(Name = "Oluşturan Kişi")]
        public Nullable<int> CreatedUserId { get; set; }

        [Display(Name = "Güncelleme Tarihi")]
        public Nullable<System.DateTime> UpdatedDate { get; set; }

        [Display(Name = "Güncelleyen Kişi")]
        public Nullable<int> UpdatedUserId { get; set; }

        public Nullable<System.DateTime> DeletedDate { get; set; }

        public Nullable<int> DeletedUserId { get; set; }

        [Display(Name = "Aktif mi")]
        public bool IsActive { get; set; }
        
        public static Categories initialize = new Categories();

        public string getUrl()
        {
            EnPratik_DataHelper db = new EnPratik_DataHelper();
            var url = db.WebSiteUrls.Where(w => w.Id == UrlId).Select(w => w.Url).FirstOrDefault();
            return url;
        }
        public Categories()
        {
            CreatedDate = DateTime.Now;
            IsActive = true;
            Published = true;
        }

        public CategoriesDTO getCategoriesDTO(string parentCategoryName)
        {
            CategoriesDTO result = new CategoriesDTO();
            result.Id = Id;
            result.ParentId = ParentId;
            result.ParentCategoryName = parentCategoryName;
            result.CategoryName = CategoryName;
            result.UrlId = UrlId;
            result.CategoryDescription = CategoryDescription;
            result.CategoryImageUrl = CategoryImageUrl;
            result.Published = Published;
            result.DisplayOrder = DisplayOrder;
            result.CreatedDate = CreatedDate;
            return result;
        }

    }


    public partial class CategoriesDTO
    {
        public int Id { get; set; }

        [Display(Name = "Üst Kategori")]
        public Nullable<int> ParentId { get; set; }

        [Display(Name = "Üst Kategori Adı")]
        public string ParentCategoryName { get; set; }

        [Display(Name = "Kategori Adı")]
        public string CategoryName { get; set; }

        public int UrlId { get; set; }

        [Display(Name = "Kategori Açıklama")]
        public string CategoryDescription { get; set; }

        [Display(Name = "Kategori Resim")]
        public string CategoryImageUrl { get; set; }

        [Display(Name = "Yayınla")]
        public bool Published { get; set; }

        [Display(Name = "Görüntüleme Sırası")]
        public Nullable<int> DisplayOrder { get; set; }

        [Display(Name = "Oluşturulma Tarihi")]
        public Nullable<System.DateTime> CreatedDate { get; set; }

        
    }
}
