//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enpratik.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Countries
    {
        public int Id { get; set; }
        [Display(Name = "Ülke Kodu")]
        public string CountryCode { get; set; }
        [Display(Name = "Ülke Adı")]
        public string CountryName { get; set; }
        public Nullable<int> LanguageId { get; set; }
        [Display(Name = "Para Birimi")]
        public Nullable<int> CurrencyId { get; set; }
        [Display(Name = "Ürün Para Tipi")]
        public Nullable<int> ProductPriceType { get; set; }
        [Display(Name = "Aktif mi")]
        public Nullable<bool> IsActive { get; set; }
    }
}
