//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enpratik.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomersRole
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string SystemName { get; set; }
        public Nullable<bool> FreeShipping { get; set; }
        public Nullable<int> TaxDisplayTypeId { get; set; }
        public Nullable<bool> TaxExempt { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
