//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enpratik.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Customers
    {
        public int Id { get; set; }
        [Display(Name = "Müşteri Tipi")]
        [Required(ErrorMessage = "Müşteri Tipi Seçiniz!")]
        public int CustomerType { get; set; }
        [Display(Name = "Ad")]
        [Required(ErrorMessage = "Ad Giriniz!")]
        public string FirstName { get; set; }
        [Display(Name = "Soyad")]
        [Required(ErrorMessage = "Soyad Giriniz!")]
        public string LastName { get; set; }
        [Display(Name = "Email")]
        [Required(ErrorMessage = "Email Giriniz!")]
        public string Mail { get; set; }
        [Display(Name = "Doğum Tarihi")]
        public Nullable<System.DateTime> BirthDate { get; set; }
        [Display(Name = "Cinsiyet")]
        public Nullable<int> Gender { get; set; }
        [Display(Name = "Telefon")]
        public string PhoneNumber { get; set; }
        [Display(Name = "Şifre")]
        [Required(ErrorMessage = "Şifre Giriniz!")]
        public string Password { get; set; }
        [Display(Name = "Durum")]
        public int Status { get; set; }
        [Display(Name = "Kayıt Tarihi")]
        public System.DateTime CreatedDate { get; set; }
        [Display(Name = "Güncelleme Tarihi")]
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        [Display(Name = "Aktif mi")]
        public bool IsActive { get; set; }
    }
}
