//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enpratik.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Districts
    {
        public int Id { get; set; }
        [Display(Name = "İl Adı")]
        [Required(ErrorMessage = "İl Seçiniz!")]
        public Nullable<int> ProvinceId { get; set; }
        [Display(Name = "İlçe Adı")]
        [Required(ErrorMessage = "İlçe Adı Giriniz!")]
        public string DistrictName { get; set; }
        [Display(Name = "Aktif mi")]
        public Nullable<bool> IsActive { get; set; }
    }
}
