//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enpratik.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Languages
    {
        public int Id { get; set; }
        [Display(Name = "Dil Adı")]
        [Required(ErrorMessage = "Dil Adı Giriniz!")]
        public string LanguageName { get; set; }
        [Display(Name = "Dil Kodu")]
        public string LanguageCode { get; set; }
        [Display(Name = "Culture Kodu")]
        public string LanguageCulture { get; set; }
        [Display(Name = "Aktif mi")]
        public Nullable<bool> IsActive { get; set; }
    }
}
