//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enpratik.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MoneyPointsSettings
    {
        public int Id { get; set; }
        [Display(Name = "Döviz Kuru")]
        public Nullable<int> ExchangeRate { get; set; }
        [Display(Name = "Ödül Puanı")]
        public Nullable<double> RewardPoint { get; set; }
        [Display(Name = "Puanları Yuvarla")]
        public Nullable<bool> RoundDownPoints { get; set; }
        [Display(Name = "Kayıt Durumunda Puan")]
        public Nullable<double> PointsForRegistration { get; set; }
        [Display(Name = "Ürün Değerlendirmesi İçin Puan")]
        public Nullable<double> PointsForAProductReview { get; set; }


        // {{Satın almalardan kazanılan puanlar}} 
        // Her biri {{SpentWillEarn}} tatarındaki alışverişe {{EarnedPoints}} puan hediye
        //

        public Nullable<double> SpentWillEarn { get; set; } 
        public Nullable<double> EarnedPoints { get; set; }
        [Display(Name = "Ödüllendirilme Anındaki Sipariş Durumu")]
        public Nullable<int> AwardedOrderStatus { get; set; }
        [Display(Name = "İptal Edilen Sipariş Durumu")]
        public Nullable<int> CanceledOrderStatus { get; set; }
        [Display(Name = "Güncelleyen Kişi")]
        public Nullable<int> UpdatedUserId { get; set; }
        [Display(Name = "Güncelleme Tarihi")]
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        [Display(Name = "Aktif mi")]
        public Nullable<bool> IsActive { get; set; }
    }
}
