//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enpratik.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Orders
    {
        public int Id { get; set; }
        [Display(Name = "Müşteri")]
        public Nullable<int> CustomerId { get; set; }
        [Display(Name = "Sipariş No")]
        public string OrderNumber { get; set; }
        [Display(Name = "Ödeme Tipi")]
        public Nullable<int> PaymentTypeId { get; set; }
        [Display(Name = "Kredi Kartı")]
        public Nullable<int> CreditCardId { get; set; }
        [Display(Name = "Taksit Miktarı")]
        public Nullable<int> InstallmentAmountId { get; set; }
        [Display(Name = "Taksit İndirimi")]
        public Nullable<double> InstallmentDiscount { get; set; }
        [Display(Name = "Hediye Paketi")]
        public Nullable<bool> IsGiftPackage { get; set; }
        [Display(Name = "Kargo Firması")]
        public string CargoCompany { get; set; }
        [Display(Name = "Kargo Parası")]
        public Nullable<double> CargoPrice { get; set; }
        [Display(Name = "Kargo Takip No")]
        public string CargoNumber { get; set; }
        [Display(Name = "Kargoya Verilme Tarihi")]
        public Nullable<System.DateTime> CargoDate { get; set; }
        [Display(Name = "Onay Tarihi")]
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        [Display(Name = "Onaylayan")]
        public string ApprovalUser { get; set; }
        [Display(Name = "Teslim Tarihi")]
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        [Display(Name = "Teslim İşlemini Yapan")]
        public string DeliveyUser { get; set; }
        [Display(Name = "İptal Edilme Tarihi")]
        public Nullable<System.DateTime> CancellationDate { get; set; }
        [Display(Name = "İptal İşlemini Yapan")]
        public string CancellationUser { get; set; }
        [Display(Name = "İptal Edilme Nedeni")]
        public string CancellationText { get; set; }
        [Display(Name = "Açıklama")]
        public string OrderDescription { get; set; }
        [Display(Name = "Teslimat Adresi")]
        public Nullable<int> DeliveryAddressId { get; set; }
        [Display(Name = "Fatura Adresi")]
        public Nullable<int> InvoiceAddressId { get; set; }
        [Display(Name = "Toplam Ödenen Tutar")]
        public Nullable<double> TotalPrice { get; set; }
        [Display(Name = "Kazanılan Puan")]
        public Nullable<double> UsedPoints { get; set; }
        [Display(Name = "Sipariş Adımlarında Bilgilendir")]
        public Nullable<bool> LetMeKnowByStep { get; set; }
        [Display(Name = "Kayıt Tarihi")]
        public Nullable<System.DateTime> CreatedDate { get; set; }
        [Display(Name = "Aktif mi")]
        public Nullable<bool> IsActive { get; set; }
    }
}
