//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enpratik.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OrderProductMapping
    {
        public int Id { get; set; }
        [Display(Name = "Sipariş Id")]
        public int OrderId { get; set; }
        [Display(Name = "Kategori Adı")]
        public string CategoryName { get; set; }
        [Display(Name = "Marka Adı")]
        public string BrandName { get; set; }
        [Display(Name = "Üretici Firma")]
        public string ManufacturerName { get; set; }
        [Display(Name = "İthalatçı Firma")]
        public string ImporterCompanyName { get; set; }
        [Display(Name = "Ürün Adı")]
        public string ProductName { get; set; }
        [Display(Name = "Barkod")]
        public string Barcode { get; set; }
        [Display(Name = "Stok No")]
        public string StockNumber { get; set; }
        [Display(Name = "Promosyon Ürün")]
        public Nullable<bool> IsPromotionProduct { get; set; }
        [Display(Name = "Ürün Fiyatı")]
        public Nullable<double> ProductPrice { get; set; }
        [Display(Name = "Ürün Resim")]
        public string ProductPictureUrl { get; set; }
        [Display(Name = "Miktar")]
        public Nullable<int> Amount { get; set; }
        [Display(Name = "Para Birimi")]
        public string CurrencyCode { get; set; }
        [Display(Name = "TL Değeri")]
        public Nullable<double> CurrencyPrice { get; set; }
        [Display(Name = "KDV")]
        public Nullable<double> Tax { get; set; }
        [Display(Name = "Havale İndirimi")]
        public Nullable<double> MoneyOrderDiscount { get; set; }
        [Display(Name = "Toplam Tutar")]
        public Nullable<double> TotalPrice { get; set; }
        [Display(Name = "Kayıt Tarihi")]
        public Nullable<System.DateTime> CreatedDate { get; set; }
        [Display(Name = "Aktif mi")]
        public Nullable<bool> IsActive { get; set; }
    }
}
