//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enpratik.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMethods
    {
        public int Id { get; set; }
        public string PaymentMethodName { get; set; }
        public string Descriptions { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
