//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enpratik.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Product_VariantAttribute_Mapping
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int VariantAttributeId { get; set; }
        public int VariantAttributeValueId { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<double> ProductPrice { get; set; }
        public Nullable<int> Tax { get; set; }
        public Nullable<bool> IsFreeShipping { get; set; }
        public Nullable<int> StockQuantity { get; set; }
        public bool IsActive { get; set; }

        public Product_VariantAttribute_Mapping() {
            IsActive = true;
        }
    }
    public partial class Product_VariantAttribute_MappingDTO
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int VariantAttributeId { get; set; }
        public int VariantAttributeValueId { get; set; }
        public string ImageUrl { get; set; }
        public string VariantAttributeName { get; set; }
        public string VariantAttributeValueName { get; set; }
        public string ColorSquaresRgb { get; set; }
        public Nullable<bool> IsCustomerEntersValue { get; set; }
        public Nullable<double> ProductPrice { get; set; }
        public Nullable<int> Tax { get; set; }
        public Nullable<bool> IsFreeShipping { get; set; }
        public Nullable<int> StockQuantity { get; set; }
        public bool IsActive { get; set; }



    }
}
