//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enpratik.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product_VariantAttributeValue
    {
        public int Id { get; set; }
        public int ProductVariantAttributeId { get; set; }

        [Display(Name = "Özellik Adı")]
        [Required(ErrorMessage = "Lütfen Özellik Adı Giriniz!")]
        public string Name { get; set; }

        [Display(Name = "Renk Kodu")]
        public string ColorSquaresRgb { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    }
}
