//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enpratik.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product_Comments
    {
        public int Id { get; set; }

        [Display(Name = "Bağlı Yorum")]
        public int ParentId { get; set; }

        [Display(Name = "Ürün")]
        public int ProductId { get; set; }

        [Display(Name = "Üye Bilgisi")]
        public int CustomerId { get; set; }

        [Display(Name = "Mesaj")]
        [Required(ErrorMessage = "Lütfen mesaj giriniz!")]
        public string CommentMessage { get; set; }

        [Display(Name = "Puanınız")]
        public Nullable<int> ProductPoint { get; set; }

        [Display(Name = "Kayıt Tarihi")]
        public Nullable<System.DateTime> CreatedDate { get; set; }

        [Display(Name = "Onay Durumu")]
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> IsActive { get; set; }


        public static Product_Comments initialize = new Product_Comments();

        public Product_Comments()
        {
            CreatedDate = DateTime.Now;
            IsActive = true;
            Status = false;
        }
    }
}
