//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enpratik.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Product_VariantProduct_Mapping
    {
        public int Id { get; set; }
        public int VariantAttributeMappingId { get; set; }
        public int ProductId { get; set; }
        public bool IsActive { get; set; }

        public Product_VariantProduct_Mapping()
        {
            IsActive = true;
        }
    }
}

