//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enpratik.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product_VariantAttribute
    {
        public int Id { get; set; }

        [Display(Name = "Varyant Adı")]
        [Required(ErrorMessage = "Kategori Adı Giriniz!")]
        public string Name { get; set; }

        [Display(Name = "Varyant Açıklaması")]
        public string Description { get; set; }

        [Display(Name = "Değeri Müşteri Girer")]
        public bool IsCustomerEntersValue { get; set; }

        [Display(Name = "Kayıt Tarihi")]
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> DeletedUserId { get; set; }
        public Nullable<bool> IsActive { get; set; }

        public static Product_VariantAttribute initialize = new Product_VariantAttribute();
        public Product_VariantAttribute() {
            CreatedDate = DateTime.Now;
            IsActive = true;
            IsCustomerEntersValue = false;
        }

    }

    public class VariantAttributeList {

        public int Id{ get; set; }
        public string Name { get; set; }

        public bool isChecked { get; set; }
    }

}
