//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enpratik.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product_Picture_Mapping
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        [Display(Name = "Ürün Resim")]
        public string ImageUrl { get; set; }
        [Display(Name = "Alt Text")]
        public string AltText { get; set; }
        [Display(Name = "Küçük Resim")]
        public Nullable<bool> IsSmallImage { get; set; }
        [Display(Name = "Varsayılan Resim")]
        public Nullable<bool> IsProductImage { get; set; }
        [Display(Name = "Görüntülenme Sırası")]
        public Nullable<int> OrderIndex { get; set; }
        [Display(Name = "Kayıt Tarihi")]
        public Nullable<DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
    }
}
