//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enpratik.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotions
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> DiscountTypeId { get; set; }
        public Nullable<bool> UsePercentage { get; set; }
        public Nullable<double> DiscountPercentage { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> RequiresCouponCode { get; set; }
        public string CouponCode { get; set; }
        public Nullable<int> DiscountLimitationId { get; set; }
        public Nullable<int> LimitationTimes { get; set; }
    }
}
