//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enpratik.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionsRequirements
    {
        public int Id { get; set; }
        public Nullable<int> RequirementTypeId { get; set; }
        public Nullable<int> CustomerRoleId { get; set; }
        public Nullable<int> BillingCountryId { get; set; }
        public Nullable<int> ShippingCountryId { get; set; }
        public string RestrictedProducts { get; set; }
        public Nullable<double> AmountSpent { get; set; }
        public string PaymentMethodIds { get; set; }
        public string CargoCompanyIds { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> DeletedUserId { get; set; }
        public bool IsActive { get; set; }
    }
}
