//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enpratik.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SendMailTemplates
    {
        public int Id { get; set; }
        [Display(Name = "Tasarım Adı")]
        [Required(ErrorMessage = "Tasarım adı giriniz!")]
        public string TemplateName { get; set; }
        public string TemplateTop { get; set; }

        [Display(Name = "Tasarım")]
        [Required(ErrorMessage = "Tasarım Giriniz!")]
        public string TemplateContent { get; set; }
        public string TemplateBottom { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> DeletedUserId { get; set; }
        public bool IsActive { get; set; }
    }
}
